services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=product_maagement'
      - 'POSTGRES_PASSWORD=gajah'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
